In [2]:
import pandas as pd

In [3]:
# df에 auto-mpg.csv 불러오기
df = pd.read_csv("../Data/auto-mpg.csv")
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [4]:
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

#### 자동차 연비 DataSet
- mpg(miles per galon) : 연비 (kpl :kilometer per liter)
- cylinders : 실린더 수 
- displacement : 배기량
- horsepower : 마력
- weight : 차중
- accelaration : 가속능력
- model year : 출시년도
- origin : 제조국 (1: USA, 2:EU, 3:JPN)
- name : 모델명

In [5]:
# Data 외형
df.shape

(398, 9)

In [6]:
# Data의 내부구조
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

> horsepower의 dtype이 Object ????

#### horsepower의 전처리(Preprocessing)

In [11]:
# 중첩 자료 제거후 확인하기

df.horsepower.unique()

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', '?', '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

> ?가 포함되어 있다.

In [ ]:
# ?인 데이터 제거
df[df.horsepower == '?']
len(df[df.horsepower == '?'])

6

> ?인 데이터가 6개 있다. -> 제거하자

In [17]:
dropIndex = df[df.horsepower == '?'].index
dropIndex

Index([32, 126, 330, 336, 354, 374], dtype='int64')

In [18]:
# 제거하기
df.drop(
    dropIndex,
    axis='rows',
    inplace=True
)
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [19]:
# 확인
df[df.horsepower == '?']

Empty DataFrame
Columns: [mpg, cylinders, displacement, horsepower, weight, acceleration, model year, origin, name]
Index: []

In [22]:
df.loc[30:35,:]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
30,28.0,4,140.0,90.00,2264.0,15.5,71,1,chevrolet vega 2300
31,25.0,4,113.0,95.00,2228.0,14.0,71,3,toyota corona
33,19.0,6,232.0,100.0,2634.0,13.0,71,1,amc gremlin
34,16.0,6,225.0,105.0,3439.0,15.5,71,1,plymouth satellite custom
35,17.0,6,250.0,100.0,3329.0,15.5,71,1,chevrolet chevelle malibu

In [24]:
# Index 재정리
df.reset_index(drop=True, inplace=True)
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [25]:
df.loc[30:35,:]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
30,28.0,4,140.0,90.00,2264.0,15.5,71,1,chevrolet vega 2300
31,25.0,4,113.0,95.00,2228.0,14.0,71,3,toyota corona
32,19.0,6,232.0,100.0,2634.0,13.0,71,1,amc gremlin
33,16.0,6,225.0,105.0,3439.0,15.5,71,1,plymouth satellite custom
34,17.0,6,250.0,100.0,3329.0,15.5,71,1,chevrolet chevelle malibu
35,19.0,6,250.0,88.00,3302.0,15.5,71,1,ford torino 500

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392 entries, 0 to 391
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    object
 4   weight        392 non-null    float64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64
 7   origin        392 non-null    int64
 8   name          392 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 27.7+ KB

In [27]:
df.horsepower.dtype

dtype('O')

> 제거는 되었으나 아직 Object Type이다.